// Renders the case report + chain-of-custody hashes to a PDF using pdfkit.
// Runs fully offline. Returns the PDF bytes so the caller hashes the exact
// bytes that get written to disk (keeping the manifest honest).

import PDFDocument from "pdfkit";
import type { CaseReport, CustodyEntry } from "./types.js";

export function renderPdf(
    report: CaseReport,
    custody: CustodyEntry[],
    rootHash: string,
): Promise<Buffer> {
    return new Promise((resolve, reject) => {
        // Deterministic creation date so the same inputs produce identical PDF
        // bytes (pdfkit otherwise stamps Date.now() into the metadata).
        const doc = new PDFDocument({
            margin: 50,
            info: {
                Title: `Tattletale Replay Report — ${report.handle}`,
                Author: "Tattletale (replay mode)",
                CreationDate: new Date(report.generatedAt),
            },
        });

        const chunks: Buffer[] = [];
        doc.on("data", (c: Buffer) => chunks.push(c));
        doc.on("end", () => resolve(Buffer.concat(chunks)));
        doc.on("error", reject);

        const blue = "#2563eb";
        const gray = "#6b7280";

        // Header
        doc.fillColor(blue).fontSize(22).text("Tattletale — OSINT Case Report");
        doc.moveDown(0.2);
        doc.fillColor(gray).fontSize(10).text("REPLAY MODE · 100% SYNTHETIC DATA · NO LIVE SCRAPE");
        doc.moveDown(0.5);
        doc.fillColor("#111827").fontSize(14).text(`${report.target.displayName}  (@${report.handle})`);
        doc.fillColor(gray).fontSize(10).text(report.target.summary);
        doc.text(`Generated: ${report.generatedAt}`);
        doc.text(`Platforms covered: ${report.platformCount}`);
        doc.moveDown(0.5);
        doc.fillColor("#b91c1c")
            .fontSize(9)
            .text(report.notice);
        doc.moveDown(1);

        // Intelligence brief (LLM-summarized or extractive; fact-validated)
        doc.fillColor(blue).fontSize(14).text("Intelligence brief");
        doc.fillColor(gray)
            .fontSize(8)
            .text(
                `Generated by: ${report.brief.generator} · every name and number below is validated against the structured case facts (no hallucinated detail).`,
            );
        doc.moveDown(0.3);
        doc.fillColor("#111827").fontSize(11).text(report.brief.text, { align: "left", lineGap: 2 });
        doc.moveDown(1);

        // Findings
        doc.fillColor(blue).fontSize(14).text("Per-platform findings");
        doc.moveDown(0.3);
        for (const f of report.findings) {
            doc.fillColor("#111827")
                .fontSize(12)
                .text(`${f.platform.toUpperCase()}  ·  @${f.username}${f.verified ? "  (verified)" : ""}`);
            doc.fillColor(gray).fontSize(9);
            doc.text(`${f.displayName} — ${f.bio}`);
            doc.text(
                `Followers: ${f.metrics.followers.toLocaleString()}   Following: ${f.metrics.following.toLocaleString()}   Posts: ${f.metrics.posts.toLocaleString()}`,
            );
            doc.text(`URL: ${f.url}`);
            for (const p of f.samplePosts) {
                doc.fillColor("#374151").fontSize(9).text(`  • [${p.timestamp}] ${p.caption}`, { indent: 8 });
            }
            doc.moveDown(0.5);
        }

        // Cross-identity correlation (computed)
        doc.moveDown(0.3);
        doc.fillColor(blue).fontSize(14).text("Cross-identity correlation");
        doc.fillColor(gray)
            .fontSize(8)
            .text(report.correlation.method);
        doc.moveDown(0.3);
        for (const id of report.correlation.identities) {
            const accts = id.accountIndices
                .map((i) => `@${report.correlation.nodes[i].username} (${report.correlation.nodes[i].platform})`)
                .join(", ");
            const span = id.accountIndices.length > 1 ? `${id.accountIndices.length} accounts` : "single account";
            const cohesion = id.cohesion === null ? "n/a (single account)" : `cohesion ${id.cohesion}`;
            doc.fillColor("#111827")
                .fontSize(10)
                .text(`Identity: ${id.label}  —  ${span}  (${cohesion})`);
            doc.fillColor(gray).fontSize(9).text(`   ${accts}`);
        }
        doc.moveDown(0.4);
        doc.fillColor("#111827").fontSize(11).text("Strongest links (with evidence):");
        for (const e of report.correlation.edges.slice(0, 6)) {
            const a = report.correlation.nodes[e.source];
            const b = report.correlation.nodes[e.target];
            doc.fillColor("#111827")
                .fontSize(9)
                .text(`  @${a.username} (${a.platform}) ↔ @${b.username} (${b.platform})  —  score ${e.score} [${e.band.toUpperCase()}]`);
            doc.fillColor(gray).fontSize(8).text(`     ${e.rationale}`);
        }
        doc.moveDown(1);

        // Chain of custody
        doc.addPage();
        doc.fillColor(blue).fontSize(14).text("Chain of custody");
        doc.fillColor(gray)
            .fontSize(9)
            .text(
                "Append-only SHA-256 hash chain. Each entry binds an artifact's content hash to the previous entry, so any tampering or reordering breaks the root hash below.",
            );
        doc.moveDown(0.5);
        for (const e of custody) {
            doc.fillColor("#111827").fontSize(10).text(`#${e.seq}  ${e.step}  —  ${e.artifact}`);
            doc.fillColor(gray).fontSize(8);
            doc.text(`   sha256:   ${e.sha256}`);
            doc.text(`   prevHash: ${e.prevHash}`);
            doc.text(`   entry:    ${e.entryHash}`);
            doc.moveDown(0.3);
        }
        doc.moveDown(0.5);
        doc.fillColor("#b91c1c").fontSize(11).text("INTERIM ROOT HASH (report + correlation):");
        doc.fillColor("#111827").fontSize(9).text(rootHash);
        doc.moveDown(0.4);
        doc.fillColor(gray)
            .fontSize(8)
            .text(
                "This PDF is hashed AFTER it is rendered, so it cannot contain the final root that " +
                    "covers itself (that would be circular). The hash above seals the report and " +
                    "correlation. The FINAL root hash — covering this PDF too — and its Ed25519 " +
                    "signature live in manifest.json / custody-log.json; verify there with the " +
                    "embedded public key.",
            );

        doc.end();
    });
}
